name: emacs2nix
version: 0.1.0.0
synopsis: Generate Nix expressions for Emacs packages
description: |
  melpa2nix uses package recipes provided by MELPA to generate Nix expressions used in Nixpkgs.

  elpa2nix generates Nix expressions from ELPA.
license: GPL-3
license-file: LICENSE
author: Thomas Tuegel
maintainer: ttuegel@mailbox.org
copyright: (C) 2018  Thomas Tuegel
category: Distribution

github: ttuegel/emacs2nix

data-files:
  - scripts/*.el

dependencies:
  - base >= 4.7 && < 5
  - aeson >= 0.8
  - ansi-wl-pprint >= 0.6
  - async >= 2.0
  - attoparsec >= 0.13
  - bytestring >= 0.10
  - containers >= 0.5
  - data-fix >= 0.0.1
  - directory >= 1.2
  - errors >= 2
  - exceptions >= 0.8
  - filepath >= 1.3
  - hashable >= 1.2
  - hnix
  - http-streams >= 0.7.2.0
  - io-streams >= 1.3
  - scientific >= 0.3
  - taggy >= 0.2
  - template-haskell >= 2.12
  - temporary >= 1.2
  - text >= 1.2
  - time >= 1.5
  - transformers >= 0.4
  - unordered-containers >= 0.2
  - uri-encode >= 1.5

ghc-options: -Wall

library:
  exposed-modules:
    - Distribution.Bzr
    - Distribution.Elpa
    - Distribution.Git
    - Distribution.Hg
    - Distribution.Emacs.Name
    - Distribution.Melpa
    - Distribution.Melpa.Fetcher
    - Distribution.Melpa.Melpa
    - Distribution.Melpa.PkgInfo
    - Distribution.Nix.Builtin
    - Distribution.Nix.Exception
    - Distribution.Nix.Fetch
    - Distribution.Nix.Hash
    - Distribution.Nix.Index
    - Distribution.Nix.Name
    - Distribution.Nix.Package.Elpa
    - Distribution.Nix.Package.Melpa
    - Distribution.SVN
    - Distribution.Wiki
    - Exceptions
    - Process
  source-dirs: src

executables:
  melpa2nix:
    main: melpa2nix.hs
    ghc-options: -threaded
    dependencies:
      - emacs2nix
      - optparse-applicative >= 0.11

  elpa2nix:
    main: elpa2nix.hs
    ghc-options: -threaded
    dependencies:
      - emacs2nix
      - optparse-applicative >= 0.11
